pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'devops:latest'

steps:
- script: dotnet restore
  displayName: 'Restoring Packages'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Building Project'

- task: DotNetCoreCLI@2
  displayName: 'Testing'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- script: docker build --no-cache -f Dockerfile -t $(dockerId)/$(imageName) .
  displayName: 'Building Docker Image'

- script: |
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName)
  displayName: 'Sending Image to Docker Hub'

